### ISSUE TITLE
SSO expiry issue

### ISSUE THREAD

**Issue by plumdog** [isotoma/aws-sso-auth#54]
To track the confusing issues where some commands indicate credentials have expired, but others don't.

See #49 and #50/#51.

**Comment by plumdog** [comment]
Version 2.5.0 includes the `--force` and `--skip-expiry-check` flags.

Currently recommend that when encountering the expiry issue:
- upgrade to at least 2.5.0 (can check current version with `aws-sso-auth --version`)
- run `aws-sso-auth --skip-expiry-check --verbose` and check if that resolves the issue
- if not, run `aws-sso-auth --force --verbose` and check if that resolves the issue

If that doesn't resolve the issue, report here the results of the following:
```
$ cat ~/.aws/sso/cache/*.json  | jq -r .expiresAt
$ cat ~/.aws/cli/cache/*.json  | jq -r .Credentials.Expiration
```
along with:
- does the AWS CLI think your credentials are valid?
- if so, what tool are you using that thinks your credentials are not valid?

**Comment by dibell** [comment]
```
$ cat ~/.aws/sso/cache/*.json  | jq -r .expiresAt
2023-06-29T16:48:23Z
$ cat ~/.aws/cli/cache/*.json  | jq -r .Credentials.Expiration
cat: '/home/davidb/.aws/cli/cache/*.json': No such file or directory
$ aws s3 ls
Error loading SSO Token: Token for https://isotoma-sso.awsapps.com/start does not exist
```

**Comment by dibell** [comment]
Broken by aws-cli update to version 2.11.7
Working with 2.9.0

**Comment by plumdog** [comment]
Believe this is mitigated - as best as can be, with a workaround - in [2.8.0](https://github.com/isotoma/aws-sso-auth/releases/tag/2.8.0).

**Comment by plumdog** [comment]
Closing as fixed.
